---
- name: install util-linux
  ansible.builtin.dnf:
    name: util-linux
    state: present

- name: Ensure swap file exists.
  ansible.builtin.command: >
    {{ swap_file_create_command }}
    creates='{{ swap_file_path }}'
  async: "{{ swap_file_create_timeout_in_seconds }}"
  poll: "{{ swap_file_create_poll_period_in_seconds }}"
  register: swap_file_create

- name: Set permissions on swap file.
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Make swap file if necessary.
  ansible.builtin.command: mkswap {{ swap_file_path }}
  when: swap_file_create is changed
  register: mkswap_result

- name: Run swapon on the swap file.
  ansible.builtin.command: swapon {{ swap_file_path }}
  when:
    - mkswap_result is changed
    - not swap_role_debug

- name: Set swappiness.
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
  when:
    - not swap_role_debug
