---
- name: Manage swap file entry in fstab.
  ansible.posix.mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: "{{ swap_file_state }}"

- ansible.builtin.include_tasks: disable.yml
  when: swap_file_state == 'absent'

- ansible.builtin.include_tasks: enable.yml
  when: swap_file_state == 'present'
